channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.8.0
  - pip=22.0.3
  - nodejs=16.13.0
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - requests==2.27.1
      - unidecode==1.3.4
      - robotframework-browser==13.0.0
      - robotframework-datadriver==1.6.1
      - robotframework-pabot==2.5.3
      - robotframework-requests==0.9.3
      - robotframework-jsonlibrary==0.3.1
      - robotframework-imaplibrary2==0.4.0
      - rpaframework==15.0.0 # https://rpaframework.org/releasenotes.html
rccPostInstall:
  - rfbrowser init
