# Browser
BROWSER = 'ChromiumDesktop'
BROWSER_HEIGHT = 1080
BROWSER_LIB='chromium'
BROWSER_LIB_HEADLESS=False
BROWSER_LIB_IS_MOBILE=False
BROWSER_LIB_LOCALE='de-DE'
BROWSER_OPTIONS = ''
BROWSER_WIDTH = 1920
INNER_WINDOW_SIZE = "0x0"
MAIN_CONTEXT = ""
USER_AGENT = ""
WINDOW_SIZE= "0x0"

# URLS
LOGIN_URL = ""
MY_ACCOUNT_URL = ""